replicaCount: 1

image:
  repository: ouestfrance/k8s-vault-webhook
  tag: latest
  pullPolicy: Always

serviceAccount: k8s-vault-webhook

vault:
  address: http://127.0.0.1:8200
  agent:
    auth_mount: kubernetes
    role: k8s-vault-webhook
  pattern: secret/data/{{.Namespace}}/{{.Secret}}

webhook:
  failurePolicy: Fail

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}