replicaCount: 2

serviceAccount: k8s-vault-webhook

image:
  repository: ouestfrance/k8s-vault-webhook
  tag: latest
  pullPolicy: Always

loglevel: info
logformat: json

basicauth: []

vault:
  address: http://127.0.0.1:8200
  pattern: secret/data/{{.Namespace}}/{{.Secret}}
  agent:
    mount: kubernetes
    role: k8s-vault-webhook
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

webhook:
  failurePolicy: Fail
  namespaceSelector:
    matchLabels: {}
    matchExpressions: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443