{{ $ca := genCA "svc-cat-ca" 3650 }}
{{ $svcName := include "k8s-vault-webhook.fullname" . }}
{{ $cn := printf "%s.%s.svc" $svcName .Release.Namespace }}
{{ $altName1 := printf "%s.cluster.local" $cn }}
{{ $altName2 := printf "%s" $cn }}
{{ $server := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "k8s-vault-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  cert.pem: {{ b64enc $server.Cert }}
  key.pem: {{ b64enc $server.Key }}
  ca:  {{ b64enc $ca.Cert }}