{{ if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "k8s-vault-webhook.fullname" . }}
  labels:
    app: {{ template "k8s-vault-webhook.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "k8s-vault-webhook.name" . }}
      release: {{ .Release.Name }}
  ingress:
  - from: 
    - podSelector:
        matchLabels:
          {{ .Values.networkPolicy.matchLabel }}: {{ .Values.networkPolicy.matchValue }}
{{ if (.Values.networkPolicy.namespaceMatchLabel) and (.Values.networkPolicy.namespaceMatchValue) }}
      namespaceSelector:
        matchLabels:
          {{ .Values.networkPolicy.namespaceMatchLabel }}: {{ .Values.networkPolicy.namespaceMatchValue }}
{{ end }}
{{ end }}