{{ if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "k8s-vault-webhook.fullname" . }}
  labels: {{- include "k8s-vault-webhook.labels" . | nindent 4}}
spec:
  podSelector:
    matchLabels:
      {{- include "k8s-vault-webhook.selectorLabels" . | nindent 6 }}
  ingress:
  - from: 
    - podSelector:
        matchLabels:
          {{ .Values.networkPolicy.matchLabel }}: {{ .Values.networkPolicy.matchValue }}
{{ if (.Values.networkPolicy.namespaceMatchLabel) and (.Values.networkPolicy.namespaceMatchValue) }}
      namespaceSelector:
        matchLabels:
          {{ .Values.networkPolicy.namespaceMatchLabel }}: {{ .Values.networkPolicy.namespaceMatchValue }}
{{ end }}
{{ end }}