apiVersion: v1
kind: Service
metadata:
  name: {{include "k8s-vault-webhook.fullname" .}}
  labels: {{- include "k8s-vault-webhook.labels" . | nindent 4}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: https
      protocol: TCP
      name: https
  selector: {{- include "k8s-vault-webhook.selectorLabels" . | nindent 4}}
