{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-vault-webhook.serviceAccountName" . }}
  labels:
    {{- include "k8s-vault-webhook.labels" . | nindent 4 }}
{{- end }}
