apiVersion: v1
kind: Service
metadata:
  name: {{ template "k8s-vault-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "k8s-vault-webhook.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
      protocol: TCP
      name: {{ template "k8s-vault-webhook.fullname" . }}
  selector:
    app: {{ template "k8s-vault-webhook.name" . }}
    release: {{ .Release.Name }}
